-- =====================================================================
-- Proyecto 1 BI: Dimensiones del Data Warehouse
-- Esquema dw. Constelación de hechos con dimensiones conformadas.
-- =====================================================================

DROP TABLE IF EXISTS fact_ingreso, fact_morosidad, fact_pago, fact_credito,
    dim_concepto_ingreso, dim_rango_atraso, dim_canal_pago, dim_agencia,
    dim_producto_credito, dim_cliente, dim_tiempo CASCADE;

-- =====================================================================
-- Dimensión Tiempo
-- Grano: un día. Dimensión obligatoria del modelo; se puebla por
-- calendario (03_poblar_dim_tiempo.sql), no proviene del ETL del OLTP.
-- =====================================================================

CREATE TABLE dim_tiempo (
    sk_tiempo INT GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    anio SMALLINT NOT NULL,
    semestre SMALLINT NOT NULL,
    trimestre SMALLINT NOT NULL,
    mes SMALLINT NOT NULL,
    nombre_mes VARCHAR(15) NOT NULL,
    dia SMALLINT NOT NULL,
    dia_semana SMALLINT NOT NULL,
    nombre_dia_semana VARCHAR(15) NOT NULL,
    es_fin_de_semana BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_tiempo PRIMARY KEY (sk_tiempo),
    CONSTRAINT uq_dim_tiempo_fecha UNIQUE (fecha)
);

-- =====================================================================
-- Dimensión Cliente
-- Grano: un asociado. Desnormalizada (esquema estrella): segmento y
-- ubicación/región viajan como columnas, sin tablas satélite.
-- =====================================================================

CREATE TABLE dim_cliente (
    sk_cliente INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente_oltp INT NOT NULL,
    numero_identificacion VARCHAR(20) NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    fecha_ingreso DATE NOT NULL,
    codigo_segmento VARCHAR(10) NOT NULL,
    nombre_segmento VARCHAR(50) NOT NULL,
    provincia VARCHAR(30) NOT NULL,
    canton VARCHAR(50) NOT NULL,
    codigo_region VARCHAR(10) NOT NULL,
    nombre_region VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_cliente PRIMARY KEY (sk_cliente),
    CONSTRAINT uq_dim_cliente_oltp UNIQUE (id_cliente_oltp)
);

-- =====================================================================
-- Dimensión Producto de Crédito
-- Grano: un producto. Tipo de crédito y garantía desnormalizados.
-- =====================================================================

CREATE TABLE dim_producto_credito (
    sk_producto SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto_oltp SMALLINT NOT NULL,
    codigo_producto VARCHAR(10) NOT NULL,
    nombre_producto VARCHAR(80) NOT NULL,
    nombre_tipo_credito VARCHAR(50) NOT NULL,
    tipo_garantia VARCHAR(20) NOT NULL,
    moneda CHAR(3) NOT NULL,
    monto_minimo NUMERIC(15,2) NOT NULL,
    monto_maximo NUMERIC(15,2) NOT NULL,
    plazo_minimo_meses SMALLINT NOT NULL,
    plazo_maximo_meses SMALLINT NOT NULL,
    activo BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_producto PRIMARY KEY (sk_producto),
    CONSTRAINT uq_dim_producto_oltp UNIQUE (id_producto_oltp)
);

-- =====================================================================
-- Dimensión Agencia
-- Grano: una agencia. Ubicación/región desnormalizada.
-- =====================================================================

CREATE TABLE dim_agencia (
    sk_agencia SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    id_agencia_oltp SMALLINT NOT NULL,
    codigo_agencia VARCHAR(10) NOT NULL,
    nombre_agencia VARCHAR(80) NOT NULL,
    provincia VARCHAR(30) NOT NULL,
    canton VARCHAR(50) NOT NULL,
    codigo_region VARCHAR(10) NOT NULL,
    nombre_region VARCHAR(50) NOT NULL,
    fecha_apertura DATE NOT NULL,
    activa BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_agencia PRIMARY KEY (sk_agencia),
    CONSTRAINT uq_dim_agencia_oltp UNIQUE (id_agencia_oltp)
);

-- =====================================================================
-- Dimensión Canal de Pago
-- Grano: un canal. Usada solo por fact_pago.
-- =====================================================================

CREATE TABLE dim_canal_pago (
    sk_canal SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    id_canal_oltp SMALLINT NOT NULL,
    codigo_canal VARCHAR(10) NOT NULL,
    nombre_canal VARCHAR(50) NOT NULL,
    es_digital BOOLEAN NOT NULL,

    CONSTRAINT pk_dim_canal PRIMARY KEY (sk_canal),
    CONSTRAINT uq_dim_canal_oltp UNIQUE (id_canal_oltp)
);

-- =====================================================================
-- Dimensión Rango de Atraso
-- Grano: un rango. Usada solo por fact_morosidad.
-- =====================================================================

CREATE TABLE dim_rango_atraso (
    sk_rango SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    id_rango_oltp SMALLINT NOT NULL,
    codigo_rango VARCHAR(10) NOT NULL,
    nombre_rango VARCHAR(50) NOT NULL,
    dias_minimo SMALLINT NOT NULL,
    dias_maximo SMALLINT,

    CONSTRAINT pk_dim_rango PRIMARY KEY (sk_rango),
    CONSTRAINT uq_dim_rango_oltp UNIQUE (id_rango_oltp)
);

-- =====================================================================
-- Dimensión Concepto de Ingreso
-- Grano: un concepto (intereses ordinario/moratorio + catálogo de
-- comisiones). Usada solo por fact_ingreso.
-- =====================================================================

CREATE TABLE dim_concepto_ingreso (
    sk_concepto SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    categoria VARCHAR(10) NOT NULL,
    codigo_concepto VARCHAR(10) NOT NULL,
    nombre_concepto VARCHAR(50) NOT NULL,

    CONSTRAINT pk_dim_concepto PRIMARY KEY (sk_concepto),
    CONSTRAINT uq_dim_concepto_codigo UNIQUE (codigo_concepto),
    CONSTRAINT ck_dim_concepto_categoria CHECK (categoria IN ('INTERES', 'COMISION'))
);
