-- =====================================================================
-- Proyecto 1 BI: Tablas de Hechos del Data Warehouse
-- Esquema dw. Constelación de 4 hechos sobre las dimensiones
-- conformadas creadas en 01_dimensiones.sql.
-- =====================================================================

-- =====================================================================
-- Tabla de Hechos: Crédito
-- Grano: una fila por crédito colocado.
-- Medidas aditivas: monto_solicitado, monto_aprobado.
-- =====================================================================

CREATE TABLE fact_credito (
    sk_credito INT GENERATED BY DEFAULT AS IDENTITY,
    id_credito_oltp INT NOT NULL,
    numero_operacion VARCHAR(20) NOT NULL,
    sk_tiempo INT NOT NULL,
    sk_cliente INT NOT NULL,
    sk_producto SMALLINT NOT NULL,
    sk_agencia SMALLINT NOT NULL,
    estado_credito VARCHAR(15) NOT NULL,
    monto_solicitado NUMERIC(15,2) NOT NULL,
    monto_aprobado NUMERIC(15,2) NOT NULL,
    plazo_meses SMALLINT NOT NULL,
    tasa_interes_anual NUMERIC(5,2) NOT NULL,
    cuota_mensual NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_fact_credito PRIMARY KEY (sk_credito),
    CONSTRAINT uq_fact_credito_oltp UNIQUE (id_credito_oltp),
    CONSTRAINT fk_fact_credito_tiempo FOREIGN KEY (sk_tiempo) REFERENCES dim_tiempo (sk_tiempo),
    CONSTRAINT fk_fact_credito_cliente FOREIGN KEY (sk_cliente) REFERENCES dim_cliente (sk_cliente),
    CONSTRAINT fk_fact_credito_producto FOREIGN KEY (sk_producto) REFERENCES dim_producto_credito (sk_producto),
    CONSTRAINT fk_fact_credito_agencia FOREIGN KEY (sk_agencia) REFERENCES dim_agencia (sk_agencia)
);

-- =====================================================================
-- Tabla de Hechos: Pago
-- Grano: una fila por cuota pagada.
-- Medidas aditivas: monto_principal, monto_interes, monto_interes_moratorio.
-- monto_total NO se almacena: es derivable (suma de las tres anteriores),
-- se calcula en la consulta o en la capa analítica.
-- =====================================================================

CREATE TABLE fact_pago (
    sk_pago INT GENERATED BY DEFAULT AS IDENTITY,
    id_pago_oltp INT NOT NULL,
    id_credito_oltp INT NOT NULL,
    numero_cuota SMALLINT NOT NULL,
    sk_tiempo INT NOT NULL,
    sk_cliente INT NOT NULL,
    sk_producto SMALLINT NOT NULL,
    sk_agencia SMALLINT NOT NULL,
    sk_canal SMALLINT NOT NULL,
    dias_atraso SMALLINT NOT NULL,
    monto_principal NUMERIC(15,2) NOT NULL,
    monto_interes NUMERIC(15,2) NOT NULL,
    monto_interes_moratorio NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_fact_pago PRIMARY KEY (sk_pago),
    CONSTRAINT uq_fact_pago_oltp UNIQUE (id_pago_oltp),
    CONSTRAINT fk_fact_pago_tiempo FOREIGN KEY (sk_tiempo) REFERENCES dim_tiempo (sk_tiempo),
    CONSTRAINT fk_fact_pago_cliente FOREIGN KEY (sk_cliente) REFERENCES dim_cliente (sk_cliente),
    CONSTRAINT fk_fact_pago_producto FOREIGN KEY (sk_producto) REFERENCES dim_producto_credito (sk_producto),
    CONSTRAINT fk_fact_pago_agencia FOREIGN KEY (sk_agencia) REFERENCES dim_agencia (sk_agencia),
    CONSTRAINT fk_fact_pago_canal FOREIGN KEY (sk_canal) REFERENCES dim_canal_pago (sk_canal)
);

-- =====================================================================
-- Tabla de Hechos: Morosidad
-- Grano: una fila por crédito por cierre mensual (snapshot).
-- Medidas semi-aditivas: saldo_pendiente, monto_atrasado
-- (se suman entre créditos en un mismo corte, no entre cortes distintos).
-- =====================================================================

CREATE TABLE fact_morosidad (
    sk_morosidad INT GENERATED BY DEFAULT AS IDENTITY,
    id_morosidad_oltp INT NOT NULL,
    id_credito_oltp INT NOT NULL,
    sk_tiempo INT NOT NULL,
    sk_cliente INT NOT NULL,
    sk_producto SMALLINT NOT NULL,
    sk_agencia SMALLINT NOT NULL,
    sk_rango SMALLINT NOT NULL,
    saldo_pendiente NUMERIC(15,2) NOT NULL,
    cuotas_atrasadas SMALLINT NOT NULL,
    monto_atrasado NUMERIC(15,2) NOT NULL,
    dias_atraso SMALLINT NOT NULL,

    CONSTRAINT pk_fact_morosidad PRIMARY KEY (sk_morosidad),
    CONSTRAINT uq_fact_morosidad_oltp UNIQUE (id_morosidad_oltp),
    CONSTRAINT fk_fact_morosidad_tiempo FOREIGN KEY (sk_tiempo) REFERENCES dim_tiempo (sk_tiempo),
    CONSTRAINT fk_fact_morosidad_cliente FOREIGN KEY (sk_cliente) REFERENCES dim_cliente (sk_cliente),
    CONSTRAINT fk_fact_morosidad_producto FOREIGN KEY (sk_producto) REFERENCES dim_producto_credito (sk_producto),
    CONSTRAINT fk_fact_morosidad_agencia FOREIGN KEY (sk_agencia) REFERENCES dim_agencia (sk_agencia),
    CONSTRAINT fk_fact_morosidad_rango FOREIGN KEY (sk_rango) REFERENCES dim_rango_atraso (sk_rango)
);

-- =====================================================================
-- Tabla de Hechos: Ingreso
-- Grano: una fila por evento de ingreso financiero (interés devengado
-- o comisión cobrada) sobre un crédito.
-- Medida aditiva: monto_ingreso.
-- =====================================================================

CREATE TABLE fact_ingreso (
    sk_ingreso INT GENERATED BY DEFAULT AS IDENTITY,
    id_credito_oltp INT NOT NULL,
    sk_tiempo INT NOT NULL,
    sk_cliente INT NOT NULL,
    sk_producto SMALLINT NOT NULL,
    sk_agencia SMALLINT NOT NULL,
    sk_concepto SMALLINT NOT NULL,
    monto_ingreso NUMERIC(15,2) NOT NULL,

    CONSTRAINT pk_fact_ingreso PRIMARY KEY (sk_ingreso),
    CONSTRAINT fk_fact_ingreso_tiempo FOREIGN KEY (sk_tiempo) REFERENCES dim_tiempo (sk_tiempo),
    CONSTRAINT fk_fact_ingreso_cliente FOREIGN KEY (sk_cliente) REFERENCES dim_cliente (sk_cliente),
    CONSTRAINT fk_fact_ingreso_producto FOREIGN KEY (sk_producto) REFERENCES dim_producto_credito (sk_producto),
    CONSTRAINT fk_fact_ingreso_agencia FOREIGN KEY (sk_agencia) REFERENCES dim_agencia (sk_agencia),
    CONSTRAINT fk_fact_ingreso_concepto FOREIGN KEY (sk_concepto) REFERENCES dim_concepto_ingreso (sk_concepto)
);

-- =====================================================================
-- Índices para acelerar las consultas
-- =====================================================================

CREATE INDEX ix_fact_credito_tiempo ON fact_credito (sk_tiempo);
CREATE INDEX ix_fact_credito_cliente ON fact_credito (sk_cliente);
CREATE INDEX ix_fact_credito_producto ON fact_credito (sk_producto);
CREATE INDEX ix_fact_credito_agencia ON fact_credito (sk_agencia);

CREATE INDEX ix_fact_pago_tiempo ON fact_pago (sk_tiempo);
CREATE INDEX ix_fact_pago_cliente ON fact_pago (sk_cliente);
CREATE INDEX ix_fact_pago_producto ON fact_pago (sk_producto);
CREATE INDEX ix_fact_pago_agencia ON fact_pago (sk_agencia);
CREATE INDEX ix_fact_pago_canal ON fact_pago (sk_canal);

CREATE INDEX ix_fact_morosidad_tiempo ON fact_morosidad (sk_tiempo);
CREATE INDEX ix_fact_morosidad_cliente ON fact_morosidad (sk_cliente);
CREATE INDEX ix_fact_morosidad_producto ON fact_morosidad (sk_producto);
CREATE INDEX ix_fact_morosidad_agencia ON fact_morosidad (sk_agencia);
CREATE INDEX ix_fact_morosidad_rango ON fact_morosidad (sk_rango);

CREATE INDEX ix_fact_ingreso_tiempo ON fact_ingreso (sk_tiempo);
CREATE INDEX ix_fact_ingreso_cliente ON fact_ingreso (sk_cliente);
CREATE INDEX ix_fact_ingreso_producto ON fact_ingreso (sk_producto);
CREATE INDEX ix_fact_ingreso_agencia ON fact_ingreso (sk_agencia);
CREATE INDEX ix_fact_ingreso_concepto ON fact_ingreso (sk_concepto);
